### ISSUE TITLE
Branch Deploy Improvement

### ISSUE THREAD

**Issue by GrantBirki** [austinhodak/TheHideoutFirebase#3]
https://github.com/austinhodak/TheHideoutFirebase/blob/b8177f73aa00cc90564c8588166d29bb33ddad63/.github/workflows/branch-deploy.yml#L10

You will probably want to update your permissions like so:

```yaml
# Permissions needed for reacting and adding comments for IssueOps commands
permissions:
  pull-requests: write
  deployments: write
  contents: write
  checks: read
```

`checks: read` is needed to view the commit status checks on branches / PRs
